# Generated by Django 4.2 on 2023-05-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onemusic', '0003_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Concert_Name', models.CharField(max_length=50)),
                ('Concert_Description', models.CharField(max_length=50)),
                ('Concert_Date', models.DateField()),
                ('Concert_Price', models.CharField(max_length=50)),
                ('Concert_Venue', models.CharField(max_length=50)),
                ('Concert_Image', models.ImageField(upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onemusic.category')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onemusic.user')),
            ],
        ),
    ]
