# Generated by Django 4.2 on 2023-05-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onemusic', '0004_concert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='category',
            new_name='Category',
        ),
    ]
